### ISSUE TITLE
Configuration with name 'vaadin-run-server' not found.

### ISSUE THREAD

**Issue by Munzey** [johndevs/gradle-vaadin-plugin#277] opened 2016-10-03 16:57 UTC
My build is failing at vaadinRun task. relevant part of stack trace seems to be:

`at org.gradle.api.artifacts.ConfigurationContainer$getAt.call(Unknown Source)
        at fi.jasoft.plugin.servers.ApplicationServer.getClassPath(ApplicationServer.groovy:118)
        at fi.jasoft.plugin.servers.ApplicationServer.getProperty(ApplicationServer.groovy)
        at fi.jasoft.plugin.servers.ApplicationServer.start(ApplicationServer.groovy:156)
        at fi.jasoft.plugin.servers.ApplicationServer$start$1.callCurrent(Unknown Source)
        at fi.jasoft.plugin.servers.ApplicationServer.startAndBlock(ApplicationServer.groovy:311)
        at fi.jasoft.plugin.tasks.RunTask.run(RunTask.groovy:71)`

here's an example [gist](https://gist.github.com/Munzey/0b84dbc17f74cf197a9d3f15b26c2af3) of the build.gradle that im trying to clean/update from 10.6 to 11.4. Any ideas whats going wrong?

cheers,
Tristan

**Comment by johndevs** [comment] 2016-10-03 17:48
You have prevented the plugin to manage the dependencies at https://gist.github.com/Munzey/0b84dbc17f74cf197a9d3f15b26c2af3#file-build-gradle-L47 . This means that the plugin does not inject any dependencies in your build. You will need to create the configuration manually and add the necessery dependencies manually.

**Comment by Munzey** [comment] 2016-10-04 13:48
hi @johndevs thanks for getting back so quick 👍 

I set `manageDependencies` to true. Here is a [revised gist](https://gist.github.com/Munzey/8ac54284e8e51e2a1b472f9f3428cd19). The build now finishes with Build Successful, however its really just terminating on vaadinRun task with message:
```Server process terminated with exit code 1. See jetty.log for further details.```
Examining jetty.log I get this output:

```[ERROR] [main] INFO org.eclipse.jetty.server.Server - jetty-8.y.z-SNAPSHOT```
```[ERROR] [main] WARN org.eclipse.jetty.util.component.AbstractLifeCycle - FAILED o.e.j.w.WebAppContext{/,[file:/Users/munzey/Projects/testProject/src/main/webapp/, file:/Users/munzey/Projects/testProject/build/classes/main/]}: java.lang.NoSuchMethodError: org.eclipse.jetty.webapp.WebAppContext.getObjectFactory()Lorg/eclipse/jetty/util/DecoratedObjectFactory;```
```[ERROR] java.lang.NoSuchMethodError: org.eclipse.jetty.webapp.WebAppContext.getObjectFactory()Lorg/eclipse/jetty/util/DecoratedObjectFactory;```
```[ERROR] at org.eclipse.jetty.plus.webapp.PlusConfiguration.preConfigure(PlusConfiguration.java:51)
[ERROR] at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:457)
[ERROR] at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:493)```
```[ERROR] at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)```
```[ERROR] at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
[ERROR] at org.eclipse.jetty.server.Server.doStart(Server.java:282)```
```[ERROR] at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)```
```[ERROR] at fi.jasoft.plugin.JettyServerRunner.main(JettyServerRunner.java:78)```

first worrying snippet is `INFO org.eclipse.jetty.server.Server - jetty-8.y.z-SNAPSHOT` Does this mean I'm still running jetty 8? I checked my gradle cache (and maven .m2 just to be sure) and wiped them. i also checked gradle dependencies to make sure there were no transitive dependencies still relying on jetty 8. Ive had no luck finding the root cause of this.

Second is the method it cant recognise, is this related to the `WebAppContext handler` in [JettyServerRunner](https://github.com/johndevs/gradle-vaadin-plugin/blob/master/src/main/java/fi/jasoft/plugin/JettyServerRunner.java)? Should I have placed the jars in a specific folder for them to be recognized?

Any help you can provide would be greatly appreciated, thanks again for your time and developing a useful tool!

**Comment by johndevs** [comment] 2016-12-13 16:34
There is a lot of redundancy now in your build.gradle so it is hard to say what is going wrong. I am guessing the problem is the multiple versions of jetty the build has on the classpath.

So, what I would recommend is start with this simple *build.gradle:
```
plugins { 
    id 'fi.jasoft.plugin.vaadin' version '1.0.1' 
}

vaadin {
    logToConsole true
}

vaadinRun {
    server 'jetty'
}
```
It will automatically include all the Vaadin and Jetty dependencies you need to run your application with. You don't need to add them manually. After that just add the needed other other dependencies until you don't have them all. Once that is done and it is working for you, you can start tweaking the dependencies and see what is breaking and maybe better figure out why it is breaking for you.

 I'm closing this as the original issue with the missing configuration was resolved.

**Closed by johndevs** 2016-12-13 16:34 UTC
