### ISSUE TITLE
Vaadin 14 Flow npm support

### ISSUE THREAD

**Issue by aze-kool** [johndevs/gradle-vaadin-plugin#540] opened 2019-08-12 14:14 UTC
Hi do you have Any Plans for vaadin npm integration in your plugin?
as mentioned here in 2.1:
https://vaadin.com/tutorials/migrate-from-bower-to-npm-for-vaadin-14+

Thanks

**Comment by christoph-frick** [comment] 2019-08-13 11:15
Is this a dupe of https://github.com/devsoap/gradle-vaadin-flow/issues/240 ?

**Comment by johndevs** [comment] 2019-08-13 11:19
@christoph-frick Yes, I'll close this as a duplicate. 
@aze-kool NPM support is coming in version 1.3 of the plugin. (it is currently in the works) 

I'll close this as a duplicate.

**Closed by johndevs** 2019-08-13 11:19 UTC
