### ISSUE TITLE
Build hangs on vaadinUpdateAddonStyles

### ISSUE THREAD

**Issue by livotov** [johndevs/gradle-vaadin-plugin#205] opened 2015-11-03 15:59 UTC
For some reason, previously functional project cannot compile anymore. No changes was made, I suppose only the vaadin gradle plugin version changed since last build a month ago (just opened one project for maintenance and noticed the problem)

Here is the tail of gradle output with --info option enabled:
```
...

:server:compileJava UP-TO-DATE
:server:compileJava (Thread[main,5,main]) completed. Took 0.076 secs.
:server:vaadinUpdateAddonStyles (Thread[main,5,main]) started.
:server:vaadinUpdateAddonStyles
Executing task ':server:vaadinUpdateAddonStyles' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Updating /Users/dlivotov/IDE/sh/apps/sh-system/server/src/main/webapp/VAADIN/themes/app/addons.scss
> Building 36% > :server:vaadinUpdateAddonStyles
```

After that process stucks forever until I Ctrl+C it.
Any idea what can be wrong ?

Here is the vaadin plugin configuration:

```
apply from: 'http://plugins.jasoft.fi/vaadin.plugin'

...

vaadin {
    version = '7.5.8'
    push = false
    debug = false
    profiler = false
    manageDependencies = true
    widgetset 'ru.shifu'
    manageWidgetset = true

    plugin {
        logToConsole = true
    }
}
```

Thanks!

**Comment by livotov** [comment] 2015-11-03 16:15
It seems the problem is in this addon: 

```
compile 'org.vaadin:resetbuttonfortextfield:1.2.1'
```

If I comment it out - build runs fine. According to version number in directory, this is the last available version of the addon. However I don't know if this is vaadin plugin bug or addon bug but you might be interested to check it out to ensure there is no bug in plugin.

Thanks again !
Dmitri

**Comment by johndevs** [comment] 2015-11-04 15:31
Hi, 

I tried to reproduce this with the following simple build.gradle:
```
dependencies {
    compile 'org.vaadin:resetbuttonfortextfield:1.2.1'
}

vaadin {
    version = '7.5.8'
    push = false
    debug = false
    profiler = false
    manageDependencies = true
    widgetset 'ru.shifu'
    manageWidgetset = true

    plugin {
        logToConsole = true
    }
}
```

But I was not able to reproduce the error.

There are a couple of things that could influence this. 

First one is that the addon seems to have a transitive dependency to Vaadin 7.4.4. It shouldn't however be a problem as the plugin should be smart enough to upgrade the Vaadin version automatically to what has been defined in *vaadin.version*.  However, I don't know if the addon itself is made compatible with Vaadin 7.5.x though.

Another thing that strikes me is that this sounds a lot like https://dev.vaadin.com/ticket/17933 where eclipse also has been known to hang when compiling the theme.  The plugin uses the same SASS compiler (**com.vaadin.server.themeutils.SASSAddonImportFileCreator**) which is bundled with Vaadin so the issue could very well be the same as well. However, the framework development team hasn't been able to reproduce the issue as can be seen from the ticket.

Maybe you could run the build with the --debug flag instead of the --info flag and see if you would get any further useful information? Also maybe have a look at your SASS theme and verify that  it has not SASS errrors?

**Comment by livotov** [comment] 2015-11-05 12:33
Thanks!
sure, will try with --debug and check the theme errors and let you know

**Comment by johndevs** [comment] 2016-01-27 17:40
Closing this as I can't re-produce it. 

If this still is occurring please re-open.

**Closed by johndevs** 2016-01-27 17:40 UTC
