### ISSUE TITLE
gwt-dev-2.7.0.vaadin4.jar - jar not loaded Offending class: javax/servlet/Servlet.class

### ISSUE THREAD

**Issue by marcfasel** [johndevs/gradle-vaadin-plugin#290] opened 2016-12-06 05:23 UTC
I am using the Gradle Vaadin plgin to build my project, and Eclipse WTP to run it locally in Tomcat. During Tomcat startup I am getting the following message:

INFO: validateJarFile(/Users/admin/apache-tomcat-7.0.52/wtpwebapps/performancecentre/WEB-INF/lib/gwt-dev-2.7.0.vaadin4.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/servlet/Servlet.class

I read somewhere that it means gwt-dev-2.7.0.vaadin4.jar should be on the compiletime build path, not the runtime. I thought this is managed by the Gradle plugin? 

http://stackoverflow.com/questions/10992644/validatejarfileservlet-api-jar-jar-not-loaded-in-tomcat-using-eclipse

**Comment by johndevs** [comment] 2016-12-06 13:14
Marking this as a duplicate of #285

**Closed by johndevs** 2016-12-06 13:14 UTC
