### ISSUE TITLE
WAR file not including all vaadin files

### ISSUE THREAD

**Issue by CSBaum** [johndevs/gradle-vaadin-plugin#186] opened 2015-05-22 13:51 UTC
The VaadinRun task works fine, but i found that i tried to load the generated WAR into a separate Tomcat instance, my app doesn't load and the logs should a class not found exception for the vaadin-server classes.  I cracked open the WAR and noticed that the only vaadin jars that were included are:

* vaadin-client-compiled
* vaadin-push
* vaadin-slf4j-jdk14
* vaadin-themes

In the past i did not have this problem, i was able to build the war and deploy it. 

Respectfully,

Sean

**Comment by moberwasserlechner** [comment] 2015-05-25 20:50
I think I have the same problem but it is more general.

If I'm using this plugin, the WAR task does not include any of my **runtime** dependencies. Instead only the compile dependencies are in the generated war file.

I've seen the behaviour in Gradle 2.3 and 2.4.

BR,
Michael

**Comment by CSBaum** [comment] 2015-05-26 14:26
I downgraded my gradle to 2.1 & 2.2 and am still seeing the same behavior.  

Respectfully,

Sean

**Comment by CSBaum** [comment] 2015-05-27 20:19
I have been doing some more poking around and it looks like vaadin-server is being picked up in the 'providedCompile' and 'providedRuntime' ... could this be causing our problems?

providedCompile - Additional compile classpath for libraries that should not be part of the WAR archive.
+--- com.vaadin:vaadin-client:7.4.+ -> 7.4.6
|    +--- com.vaadin:vaadin-shared:7.4.6
|    |    +--- com.vaadin.external.flute:flute:1.3.0.gg2
|    |    +--- com.vaadin.external.streamhtmlparser:streamhtmlparser-jsilver:0.0.10.vaadin1
|    |    \--- com.vaadin.external.google:guava:16.0.1.vaadin1
|    +--- com.vaadin:vaadin-server:7.4.6
|    |    +--- com.vaadin:vaadin-sass-compiler:0.9.12
|    |    |    +--- org.w3c.css:sac:1.3
|    |    |    \--- com.vaadin.external.flute:flute:1.3.0.gg2
|    |    +--- com.vaadin:vaadin-shared:7.4.6 (*)
|    |    \--- org.jsoup:jsoup:1.8.1
|    +--- org.w3c.css:sac:1.3
|    \--- javax.validation:validation-api:1.0.0.GA
\--- javax.servlet:javax.servlet-api:3.+ -> 3.1.0

providedRuntime - Additional runtime classpath for libraries that should not be part of the WAR archive.
+--- com.vaadin:vaadin-client:7.4.+ -> 7.4.6
|    +--- com.vaadin:vaadin-shared:7.4.6
|    |    +--- com.vaadin.external.flute:flute:1.3.0.gg2
|    |    +--- com.vaadin.external.streamhtmlparser:streamhtmlparser-jsilver:0.0.10.vaadin1
|    |    \--- com.vaadin.external.google:guava:16.0.1.vaadin1
|    +--- com.vaadin:vaadin-server:7.4.6
|    |    +--- com.vaadin:vaadin-sass-compiler:0.9.12
|    |    |    +--- org.w3c.css:sac:1.3
|    |    |    \--- com.vaadin.external.flute:flute:1.3.0.gg2
|    |    +--- com.vaadin:vaadin-shared:7.4.6 (*)
|    |    \--- org.jsoup:jsoup:1.8.1
|    +--- org.w3c.css:sac:1.3
|    \--- javax.validation:validation-api:1.0.0.GA
\--- javax.servlet:javax.servlet-api:3.+ -> 3.1.0

**Comment by CSBaum** [comment] 2015-05-27 21:05
I believe that i solved the problem, by not setting the transitive property to false, Gradle was grabbing everything associated with the vaaidn-client dependency and marking them to be excluded, by changing my dependency line to --> providedCompile ('com.vaadin:vaadin-client:7.4.+') { transitive = false }   it seems to have fixed the problem.  

That being said, i have defined my own vaadin dependencies, i would think that the vaadin-plugin should handle setting the transitive flag when it's managing the dependencies....

**Comment by johndevs** [comment] 2015-07-30 18:05
If the plugin is managing the dependencies you shouldn't add vaadin dependencies yourself, the plugin will add them for you. The plugin will add the *vaadin-client* dependency automatically once you define the **vaadin.widgetset** property in your build file.

**Comment by morganc** [comment] 2015-08-24 23:42
Hi, @johndevs, and thanks for the awesome plugin.

The problem is not that vaadin dependencies are not getting added automatically.  The bug is that *no* runtime jars are not getting included.  Here's the simplest code example I can think of to demonstrate the issue, described so well by @moberwasserlechner above.

    // build.gradle
    
    repositories {
          mavenCentral()
    }
    
    apply plugin: 'war'
    apply from: "http://plugins.jasoft.fi/vaadin.plugin?version=0.10.1"
    
    dependencies {
        // This could be any RUNTIME jar
        runtime "commons-lang:commons-lang:2.6"
    }
    
    vaadin {
        widgetset "issue186.widgetset.Issue186Widgetset"
    }

When I call "gradle war", then the runtime jar I specify should wind up in WEB_INF/lib, but it does not.  The trick @CSBaum used above to specify "transitive = false" does not help me, since I'm relying on the plugin to include the vaadin jars etc.  But if I have some runtime jar I need to include, it does not show up.

**Comment by morganc** [comment] 2015-08-25 15:46
Ah!  There might be a quick and dirty fix for this.  In the TaskListener class, perhaps we need to re-add the runtime configuration if the task is "war".  (We wouldn't add it for any other tasks like "compile", say, but the war task is special.  And we only need to add it back because we overwrite the classpath when managing dependencies.)

        if (project.vaadin.manageDependencies) {
        
                // Include project classes and resources
                war.classpath = project.files(
                        project.sourceSets.main.output.classesDir,
                        project.sourceSets.main.output.resourcesDir
                )
        
                // remove duplicates and providedCompile dependencies
                war.classpath += project.configurations[Configuration.SERVER.caption]
        
                // Include push dependencies if enabled
                if(Util.isPushSupportedAndEnabled(project)) {
                    war.classpath += project.configurations[Configuration.PUSH.caption]
                }
        
                // War must include runtime jars in /WEB-INF/lib
                war.classpath += project.configurations.runtime
                // ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  ADDED
        
                // Remove providedCompile dependencies
                war.classpath -= project.configurations.providedCompile
        
                // Ensure no duplicates
                war.classpath = war.classpath.files
        }

**Closed** 2015-09-28 17:47 UTC
Labels: 0.10.2, bug
