### ISSUE TITLE
java.lang.IllegalStateException: Resolving configuration 'apiElements' directly is not allowed, Can't build vaadin project with Gradle 3.4

### ISSUE THREAD

**Issue by wodencafe** [johndevs/gradle-vaadin-plugin#331] opened 2017-02-09 20:12 UTC
Hi, we just upgraded our gradle wrapper to use 3.4-rc-2,

and find that we can no longer build our Vaadin project with this gradle-vaadin-plugin.

This is the error we get when running "./gradlew jar" or similar commands:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':DXOPManagerUI:vaadinUpdateWidgetset'.
> Resolving configuration 'apiElements' directly is not allowed

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':DXOPManagerUI:vaadinUpdateWidgetset'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
Caused by: java.lang.IllegalStateException: Resolving configuration 'apiElements' directly is not allowed
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.assertResolvingAllowed(DefaultConfiguration.java:819)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1300(DefaultConfiguration.java:106)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.<init>(DefaultConfiguration.java:773)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.<init>(DefaultConfiguration.java:792)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.<init>(DefaultConfiguration.java:767)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.fileCollection(DefaultConfiguration.java:391)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.files(DefaultConfiguration.java:371)
        at fi.jasoft.plugin.tasks.UpdateWidgetsetTask$_findInheritsInDependencies_closure2$_closure6.doCall(UpdateWidgetsetTask.groovy:141)
        at fi.jasoft.plugin.tasks.UpdateWidgetsetTask$_findInheritsInDependencies_closure2.doCall(UpdateWidgetsetTask.groovy:134)
        at fi.jasoft.plugin.tasks.UpdateWidgetsetTask.findInheritsInDependencies(UpdateWidgetsetTask.groovy:133)
        at fi.jasoft.plugin.tasks.UpdateWidgetsetTask.findInheritsInDependencies(UpdateWidgetsetTask.groovy:121)
        at fi.jasoft.plugin.tasks.UpdateWidgetsetTask.getInherits(UpdateWidgetsetTask.groovy:235)
        at fi.jasoft.plugin.tasks.UpdateWidgetsetTask.updateWidgetset(UpdateWidgetsetTask.groovy:95)
        at fi.jasoft.plugin.tasks.UpdateWidgetsetTask.ensureWidgetPresent(UpdateWidgetsetTask.groovy:86)
        at fi.jasoft.plugin.tasks.UpdateWidgetsetTask.ensureWidgetPresent(UpdateWidgetsetTask.groovy:70)
        at fi.jasoft.plugin.tasks.UpdateWidgetsetTask.run(UpdateWidgetsetTask.groovy:66)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 20 more


BUILD FAILED
```

This works fine when using earlier versions of Gradle.

I found this thread talking about the issue, it looks like this was caused by a conscious change in Gradle (they don't consider it a bug, but rather a change)

https://discuss.gradle.org/t/3-4-rc-1-3-3-resolving-configurations-may-be-disallowed-and-throw-illegalstateexception/21470

**Comment by johndevs** [comment] 2017-02-11 08:12
I can seem to reproduce this with a basic project at least.

The stacktrace seems to indicate that it is trying to resolve a configuration named "apiElements", is that something custom to your project? Would it be possible for you to upload the build.gradle that defines that configuration?

**Comment by aley2003** [comment] 2017-02-23 11:46
I have the same problem with Gradle 3.4. 
Attached is a simple test project which reproduces the error.
[TestGradleVaadinPlugin.zip](https://github.com/johndevs/gradle-vaadin-plugin/files/796350/TestGradleVaadinPlugin.zip)

**Comment by lanejo01** [comment] 2017-02-23 18:34
We are seeing the same issue as @aley2003 and @wodencafe . The issue is due to a change in gradle, I believe they said it started on gradle version 3.3. Here are the release notes from gradle 3.4 where they state that this is a breaking change. https://docs.gradle.org/3.4/release-notes.html#configurations-can-be-unresolvable

**Comment by iboyko** [comment] 2017-02-24 09:55
+1

**Comment by johndevs** [comment] 2017-02-24 18:57
@aley2003 Thanks for the example project!

Fixing this for the next maintenance release.

**Comment by wodencafe** [comment] 2017-02-25 17:11
@johndevs Good work sir

**Comment by aley2003** [comment] 2017-02-27 11:46
Should this bug be resolved?
I still get the 'Resolving configuration 'apiElements' directly is not allowed' error message with 1.1.5 when I try to build my project with Gradle 3.4.

**Comment by johndevs** [comment] 2017-02-27 12:03
Yes, it should be resolved in 1.1.5. Could you post a stacktrace?

**Comment by aley2003** [comment] 2017-02-27 12:52
Here is the stacktrace
`* What went wrong:
A problem occurred configuring project ':theme'.
> Resolving configuration 'apiElements' directly is not allowed

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':biocontrol-theme'.
        at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:94)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:89)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:76)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:53)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:50)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:599)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:125)
        at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:62)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
        at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuildAction.execute(DefaultGradleLauncher.java:233)
        at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuildAction.execute(DefaultGradleLauncher.java:230)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:160)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:31)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
Caused by: java.lang.IllegalStateException: Resolving configuration 'apiElements' directly is not allowed
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.assertResolvingAllowed(DefaultConfiguration.java:819)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:419)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getResolvedConfiguration(DefaultConfiguration.java:414)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getResolvedConfiguration(Unknown Source)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:213)
        at org.gradle.internal.metaobject.BeanDynamicObject.getProperty(BeanDynamicObject.java:156)
        at org.gradle.internal.metaobject.CompositeDynamicObject.getProperty(CompositeDynamicObject.java:55)
        at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:60)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getProperty(Unknown Source)
        at fi.jasoft.plugin.Util$_memoizedMethodPriv_getResolvedArtifactVersionProjectStringString_closure10$_closure58.doCall(Util.groovy:633)
        at fi.jasoft.plugin.Util$_memoizedMethodPriv_getResolvedArtifactVersionProjectStringString_closure10.doCall(Util.groovy:631)
        at fi.jasoft.plugin.Util.memoizedMethodPriv$getResolvedArtifactVersionProjectStringString(Util.groovy:630)
        at fi.jasoft.plugin.Util$__clinit__closure38.doCall(Util.groovy)
        at fi.jasoft.plugin.Util.getResolvedArtifactVersion(Util.groovy)
        at fi.jasoft.plugin.Util$_memoizedMethodPriv_findAddonsInProjectProjectStringBooleanList_closure12$_closure61$_closure62$_closure63.doCall(Util.groovy:710)
        at fi.jasoft.plugin.Util$_memoizedMethodPriv_findAddonsInProjectProjectStringBooleanList_closure12$_closure61$_closure62.doCall(Util.groovy:692)
        at fi.jasoft.plugin.Util$_memoizedMethodPriv_findAddonsInProjectProjectStringBooleanList_closure12$_closure61.doCall(Util.groovy:690)
        at fi.jasoft.plugin.Util$_memoizedMethodPriv_findAddonsInProjectProjectStringBooleanList_closure12.doCall(Util.groovy:682)
        at fi.jasoft.plugin.Util.memoizedMethodPriv$findAddonsInProjectProjectStringBooleanList(Util.groovy:681)
        at fi.jasoft.plugin.Util$__clinit__closure40.doCall(Util.groovy)
        at fi.jasoft.plugin.Util.findAddonsInProject(Util.groovy)
        at fi.jasoft.plugin.Util.findAddonsInProject(Util.groovy:676)
        at fi.jasoft.plugin.Util$findAddonsInProject$10.callStatic(Unknown Source)
        at fi.jasoft.plugin.Util.memoizedMethodPriv$resolveWidgetsetFileProject(Util.groovy:931)
        at fi.jasoft.plugin.Util$__clinit__closure47.doCall(Util.groovy)
        at fi.jasoft.plugin.Util.resolveWidgetsetFile(Util.groovy)
        at fi.jasoft.plugin.Util$resolveWidgetsetFile$6.callStatic(Unknown Source)
        at fi.jasoft.plugin.Util.memoizedMethodPriv$getWidgetsetProject(Util.groovy:884)
        at fi.jasoft.plugin.Util$__clinit__closure46.doCall(Util.groovy)
        at fi.jasoft.plugin.Util.getWidgetset(Util.groovy)
        at fi.jasoft.plugin.Util$getWidgetset$5.call(Unknown Source)
        at fi.jasoft.plugin.GradleVaadinPlugin$_applyDependencies_closure4$_closure19.doCall(GradleVaadinPlugin.groovy:313)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:70)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.triggerWhenEmptyActionsIfNecessary(DefaultConfiguration.java:348)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.performPreResolveActions(DefaultConfiguration.java:478)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$500(DefaultConfiguration.java:106)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$3.execute(DefaultConfiguration.java:452)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$3.execute(DefaultConfiguration.java:446)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveGraphIfRequired(DefaultConfiguration.java:446)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:422)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.doGetFiles(DefaultConfiguration.java:515)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getFiles(DefaultConfiguration.java:367)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getFiles(Unknown Source)
        at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:68)
        at org.gradle.util.CollectionUtils.filter(CollectionUtils.java:136)
        at org.gradle.api.internal.file.AbstractFileCollection$3.getFiles(AbstractFileCollection.java:223)
        at org.gradle.api.internal.file.CompositeFileCollection.getFiles(CompositeFileCollection.java:56)
        at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:68)
        at fi.jasoft.plugin.tasks.BuildClassPathJar$_closure2.doCall(BuildClassPathJar.groovy:54)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy16.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:82)
        ... 56 more
`

**Comment by johndevs** [comment] 2017-02-27 15:53
@aley2003 Thanks! I seem to have missed one place more where it tries to resolve the apiElements dependency.

**Closed** 2017-02-27 16:54 UTC
Labels: 1.1.4, bug
