### ISSUE TITLE
Can't build multiproject with plugin 1.1.5, Gradle 3.4

### ISSUE THREAD

**Issue by wodencafe** [johndevs/gradle-vaadin-plugin#343] opened 2017-02-27 16:54 UTC
Hi all,

we are having a problem building our multi project build from our root project, using the latest gradle-vaadin-plugin 1.15

Here's the stack trace of the error we are seeing:

```
* Exception is:
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'fi.jasoft.plugin.configuration.TestBenchConfiguration_Decorated@aaf680d' with class 'fi.jasoft.plugin.configuration.TestBenchConfiguration_Decorated' to class 'fi.jasoft.plugin.configuration.TestBenchConfiguration'
        at fi.jasoft.plugin.TaskListener.configureTest(TaskListener.groovy:235)
        at fi.jasoft.plugin.TaskListener.beforeExecute(TaskListener.groovy:70)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy56.beforeExecute(Unknown Source)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:202)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:74)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:55)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)

```

**Comment by johndevs** [comment] 2017-05-02 17:28
Could you check your ``settings.gradle`` that you are not applying any plugins there?

**Comment by johndevs** [comment] 2017-06-04 07:46
Considering this a duplicate of #384

**Closed by johndevs** 2017-06-04 07:46 UTC
Labels: unverified
