### ISSUE TITLE
java.lang.IllegalStateException: Shutdown in progress

### ISSUE THREAD

**Issue by aparod** [johndevs/gradle-vaadin-plugin#226] opened 2016-01-25 18:30 UTC
After upgrading to 0.10.5 from 0.9.8, I get the following exception after running tasks (for example, `vaadinCompileThemes`).  Note that the task does succeed, but the exception still gets thrown afterward. I am running Gradle 2.10.  Switching back to 0.9.8 gets rid of the exception.

```
gradle vaadinCompileThemes
Using Gradle Vaadin Plugin 0.10.5
:compileJava
:vaadinUpdateWidgetset
:processResources UP-TO-DATE
:classes
:vaadinClassPathJar SKIPPED
:vaadinUpdateAddonStyles
:vaadinCompileThemes

BUILD SUCCESSFUL

Total time: 7.967 secs

Exception in thread "Thread-4" java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)
	at java.lang.Runtime.removeShutdownHook(Runtime.java:239)
	at java_lang_Runtime$removeShutdownHook$2.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at fi.jasoft.plugin.tasks.SuperDevModeTask$_closure1.doCall(SuperDevModeTask.groovy:44)
	at fi.jasoft.plugin.tasks.SuperDevModeTask$_closure1.doCall(SuperDevModeTask.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at groovy.lang.Closure.call(Closure.java:426)
	at groovy.lang.Closure.call(Closure.java:420)
	at groovy.lang.Closure.run(Closure.java:507)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-3" java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)
	at java.lang.Runtime.removeShutdownHook(Runtime.java:239)
	at java_lang_Runtime$removeShutdownHook$3.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at fi.jasoft.plugin.tasks.DevModeTask$_closure1.doCall(DevModeTask.groovy:41)
	at fi.jasoft.plugin.tasks.DevModeTask$_closure1.doCall(DevModeTask.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at groovy.lang.Closure.call(Closure.java:426)
	at groovy.lang.Closure.call(Closure.java:420)
	at groovy.lang.Closure.run(Closure.java:507)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-5" java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)
	at java.lang.Runtime.removeShutdownHook(Runtime.java:239)
	at java_lang_Runtime$removeShutdownHook$3.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at fi.jasoft.plugin.tasks.RunTask$_closure1.doCall(RunTask.groovy:30)
	at fi.jasoft.plugin.tasks.RunTask$_closure1.doCall(RunTask.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at groovy.lang.Closure.call(Closure.java:426)
	at groovy.lang.Closure.call(Closure.java:420)
	at groovy.lang.Closure.run(Closure.java:507)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by johndevs** [comment] 2016-01-25 18:48
The problem is that when a task stops and you are not running in deamon mode, the JVM is already killed and the shutdown hook is not needed. 

This is fixed in the ``0.11`` along with 7d87919f674ae8aff93ae4e6b6f490f5a1b4ad80. That part of the patch needs to be backported 0.10 to fixed this.

**Closed** 2016-01-25 18:53 UTC
Labels: 0.10.6, bug
