### ISSUE TITLE
Snapshot version broke generated widgetset xml

### ISSUE THREAD

**Issue by jorgebsa** [johndevs/gradle-vaadin-plugin#241] opened 2016-04-12 03:42 UTC
Hey there, as always let me first thank you for the effort put into this plugin! ;)

Now let's get to the issue, one of my coworkers made a simple code change to one of our vaadin projects and most features related to vaadin add-ons simply stopped working. Comparing the source code, we realized that the generated widgetset xml had drastically changed. I immediately came here and noticed that you had published a new version of the plugin. By simply reverting the version to 0.10.7 the issue was fixed. 

Now comes the question, has there been any change in the widgetset generation that requires any type of variable being set on build.gradle or any other place? Or can this be an unexpected side-effect of the new version?  Right now we simply declare the widgetset variable on the vaadin block of build.gradle.

I will update this issue with the xml generated by 0.10.7 and by 0.11 ASAP

**Comment by johndevs** [comment] 2016-04-12 05:37
Hi,

Indeed just recently 0.11-beta was released to the update site which is a major release with quite a  few changes. It should however be backwards compatible so you shouldn't need to change your build.gradle for the upgrade (you will get some nagging messages in the console though asking you to update from deprecated API).

I did a quick run with a simple project without addons and didn't notice any differences, but maybe with a more complex project there might be. When you have time please post the differing xml files and I'll have another look. If they differ significantly then it is definitely a regression somewhere.

**Comment by dawiemalan** [comment] 2016-04-12 10:48
We have a similar issue. The project is a Spring Boot application, and since the upgrade to 0.11 widgetset generation does nothing. Also, push is not enabled anymore.

Here is an extract from build.gradle:

vaadin {
    version "$vaadinVersion"
    manageDependencies true
    push true
    widgetset 'UnibosWidgetSet'
//    manageWidgetset true
}

vaadinCompile.manageWidgetset true

Build output:

12:43:42 PM: Executing external task 'vaadinUpdateWidgetset'...
Using Gradle Vaadin Plugin 0.11.0-beta
The vaadin.widgetset property has been deprecated and is scheduled to be removed in Gradle Vaadin Plugin 0.12. This property has been replaced by automatic widgetset detection. You should be able to remove this property definition completely. If you do need to set it manually you can set vaadinCompile.widgetset.
:unibos-ui:vaadinUpdateWidgetset

BUILD SUCCESSFUL

Total time: 19.485 secs
12:44:02 PM: External task execution finished 'vaadinUpdateWidgetset'.

After this UnibosWidgetSet.gwt.xml is untouched, and no widgetset files in src/webapp/VAADIN.

**Comment by johndevs** [comment] 2016-04-12 11:33
Hi @dawiemalan,

> After this UnibosWidgetSet.gwt.xml is untouched, and no widgetset files in src/webapp/VAADIN.

The generated widgetset file should end up in ``src/main/resources``  and not under webapp by default. Could you check that that is the case or have you configured it somehow? If you already have a widgetset file in-place which is up-2-date then the plugin will not alter it unless something is added to the build (like an addon with a widgetset). 

> Here is the generated widget set (note no addons at all):

Should it contain addons?

> ... Also, push is not enabled anymore.

I couldn't reproduce the push issue with  a simple case, could you check ``gradle dependencies`` contains the **vaadin-push** configuration with the vaadin-push dependencies? Also ensure your UI is using the @Push annotation.

**Comment by dawiemalan** [comment] 2016-04-12 11:38
I can confirm the widgetset is created in src/main/resources. I deleted it, ran it again and the widgetset was re-created, still the same though.

Yes, there should be several addons.  I will come back to the push issue, it may be unrelated.

Here are the addon depencencies:

```
    compile 'org.vaadin.addon:easyuploads:7.4.2'
    compile 'org.vaadin.addons:vaadin-grid-util:1.0.7'
    compile 'org.vaadin.addons:popupbutton:2.6.0'
    compile 'org.vaadin.addons:contextmenu:4.5'
    compile 'org.vaadin.addons:dcharts-widget:1.7.0'
    compile 'org.vaadin.teemu:switch:2.0.3'
    compile 'org.vaadin.alump.labelbutton:labelbutton-addon:0.1.3'
    compile 'org.vaadin.alump.masonry:masonry-addon:0.5.0'

```

Something that might be relevant - these dependencies are declared in another module which this module depends on. Will try adding it to this module's build and check if there is a difference.

**Comment by dawiemalan** [comment] 2016-04-12 11:46
Adding dependencies directly to this module did not help. I added all Vaadin dependencies too, and disabled vaadin,manageDependencies.  I've got the compiled widgetset now in webapp/VAADIN/widgetsets, but UnibosWidgetSet.gwt.xml is still incomplete:

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Vaadin//DTD Vaadin 7//EN" "https://raw.github.com/vaadin/gwt/master/distro-source/core/src/gwt-module.dtd">

<module>
        <inherits name="com.vaadin.DefaultWidgetSet" />
        <set-configuration-property name="devModeRedirectEnabled" value="true" />
        <set-property name="user.agent" value="ie8,ie9,gecko1_8,safari,ie10" />
        <source path="client" />
        <source path="shared" />
        <collapse-all-properties />
        <set-property name="compiler.useSymbolMaps" value="true" />
</module>`

**Comment by johndevs** [comment] 2016-04-12 11:51
@dawiemalan Thanks for the info, can confirm it now.

**Comment by johndevs** [comment] 2016-04-12 15:35
@jorgebsa @dawiemalan Should be fixed in the 0.11-SNAPSHOT now, if you want you can try it out. I'll release a second beta next weekend to the update site with this fix included as well. Thanks for reporting this critical issue!

**Comment by dawiemalan** [comment] 2016-04-13 04:34
Still not working for me. I'm using:

`apply from: 'http://plugins.jasoft.fi/vaadin.plugin?0.11-SNAPSHOT'
`

Did a clean build, gwt-unitCache and widgetsets directories are built as expected, and the widgetset file was created, but still no add-ons in the widgetset and addons.scss is not updated.

We are a bit stuck, we need 0.11 for #216.

**Comment by johndevs** [comment] 2016-04-13 05:04
Since it is a snapshot could you add "--refresh-dependencies" when running the build to ensure you are getting the latest snapshot and not a snapshot from the gradle cache. Still same result?

**Comment by dawiemalan** [comment] 2016-04-13 05:33
Same result.

**Comment by johndevs** [comment] 2016-04-13 06:08
> Something that might be relevant - these dependencies are declared in another module which this module depends on. 

I think this is the relevant part in this particular case. Are you exposing these dependencies as transitive dependencies for the module? The plugin will only scan the dependency graph of the module it is run in and and if the module only depends on the resulting artifact of the module (with a project dependency), and the module does not provide its dependencies as transitive dependencies to that artifact then the moudle will not know that the addon dependencies needs to be included.

**Comment by dawiemalan** [comment] 2016-04-13 06:16
I thought it might be related, and therefore added the addons as direct dependencies to the UI application yesterday, before your latest fix.

Here is the complete build.gradle for this module:

```
buildscript {
    ext {
        springLoadedVersion = '1.2.4.RELEASE'
    }
    repositories {
        mavenCentral()
        jcenter()
        maven {url "http://repo.spring.io/snapshot"}
        maven {url "http://repo.spring.io/milestone"}
    }
    dependencies {
//        classpath "fi.jasoft.plugin:gradle-vaadin-plugin:0.10.7"
        classpath("org.springframework.boot:spring-boot-gradle-plugin:$springVersion")
        classpath "org.springframework:springloaded:$springLoadedVersion"
        classpath 'com.netflix.nebula:gradle-info-plugin:3.+'
    }
}

plugins {
    id 'nebula.provided-base' version '3.0.3'
//    id 'fi.jasoft.plugin.vaadin' version '0.11.0-beta'
}

apply plugin:'java'
apply plugin:'groovy'
apply plugin:'maven'
apply plugin:'idea'
apply plugin:'eclipse'
apply plugin: 'nebula.info'
apply plugin: 'spring-boot'
apply from: 'http://plugins.jasoft.fi/vaadin.plugin?0.11-SNAPSHOT'

version rootProject.version

repositories {
    mavenCentral()
}

dependencies {

    compile("org.codehaus.groovy:groovy:$groovyVersion") {
        exclude module:"commons-cli"
        exclude module:"ant"
    }

    compile "org.springframework.boot:spring-boot-starter:$springVersion"
    compile "org.springframework.boot:spring-boot-starter-web:$springVersion"
    compile "org.springframework.boot:spring-boot-starter-actuator:$springVersion"
    compile "org.springframework.boot:spring-boot-starter-security:$springVersion"

    compile 'javax.servlet:javax.servlet-api:3.1.0'
    compile 'org.hibernate:hibernate-validator:4.1.0.Final'

//    compile "com.vaadin:vaadin-spring-boot:$vaadinSpringVersion"
//    compile "com.vaadin:vaadin-server:$vaadinVersion"
//    compile "com.vaadin:vaadin-themes:$vaadinVersion"
//    compile "com.vaadin:vaadin-client:$vaadinVersion"
//    compile "com.vaadin:vaadin-client-compiled:$vaadinVersion"
//    provided "com.vaadin:vaadin-client-compiler:$vaadinVersion"
    compile "com.vaadin:vaadin-push:$vaadinVersion"
    compile 'com.vaadin.external.atmosphere:atmosphere-runtime:2.2.7.vaadin1'

    testCompile group: 'junit', name: 'junit', version: '4.11'

    compile 'org.vaadin.addon:easyuploads:7.4.2'
    compile 'org.vaadin.addons:vaadin-grid-util:1.0.7'
    compile 'org.vaadin.addons:popupbutton:2.6.0'
    compile 'org.vaadin.addons:contextmenu:4.5'
    compile 'org.vaadin.addons:dcharts-widget:1.7.0'
    compile 'org.vaadin.teemu:switch:2.0.3'
    compile 'org.vaadin.alump.labelbutton:labelbutton-addon:0.1.3'
    compile 'org.vaadin.alump.masonry:masonry-addon:0.5.0'

    compile project(':core-common')
    compile project(':core-client')
    compile project(':accounting-common')
    compile project(':accounting-client')
    compile project(':unibos-vaadin')
}

configurations.all {
    resolutionStrategy {
        force "javax.validation:validation-api:1.0.0.GA"
    }
}

jar {
    baseName = 'unibos-ui'
    version =  "$project.version"
}

compileJava.dependsOn(processResources)

//war.enabled = false
jar.enabled = false

vaadin {
    version "$vaadinVersion"
    manageDependencies true
    push true
}

vaadinCompile.widgetset 'UnibosWidgetSet'

springBoot {
    mainClass = 'unibos.ui.UnibosUIApplication'
    executable = true
}

bootRun {
    addResources = true
    systemProperties System.properties
}

bootRepackage {
    executable true
    excludeDevtools true
    //layout 'jar'
}

install.enabled false
uploadArchives.enabled false
```

**Comment by dawiemalan** [comment] 2016-04-13 06:25
I just noticed, some time this morning (probably after the --refresh-dependencies run) the addons.scss was updated.  Just did another clean build and got this in addons.scss (but widgetset still not right):

```
/* This file is automatically managed and will be overwritten from time to time. */
/* Do not manually edit this file. */

/* Provided by labelbutton-addon-0.1.3.jar */
@import "../../../VAADIN/addons/labelbutton/labelbutton.scss";


/* Provided by contextmenu-4.5.jar */
@import "../../../VAADIN/themes/contextmenu/contextmenu.scss";


/* Provided by masonry-addon-0.5.0.jar */
@import "../../../VAADIN/addons/masonry/masonry.scss";


/* Import and include this mixin into your project theme to include the addon themes */
@mixin addons {
	@include labelbutton;
	@include contextmenu;
	@include masonry;
}
```

**Comment by dawiemalan** [comment] 2016-04-14 05:49
Disabled widgetset management for now.  Will revisit this when beta-2 is available.

**Comment by johndevs** [comment] 2016-04-16 08:14
@dawiemalan Beta 2 is released. That last fix should resolve the issue with the widgetset genereration not including the inherits.

**Comment by dawiemalan** [comment] 2016-04-16 11:51
Resolved, thanks John.

**Closed** 2016-04-16 12:10 UTC
Labels: 0.11, bug
